### ISSUE TITLE
Étape 2 du formulaire - Données cliniques

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#375]
### Feature

Mettre en place l'étape 2 du formulaire de soumissions web excepté la section HPO

### Acceptance Criteria

- Les champs sont tous présents
- Le styling a été appliqué suivant la maquette Figma

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [x] Section "Analyse demandée"
- [x] Section "Résumé de l'investigation"
- [x] Section "Histoire familiale"
- [x] Section "Indications"
- [x] Section "CTA" en bas

### Testing Strategy
_Who can test it? How do we test it? What do we need to test it?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect 1
- [ ] Defect 2
- [ ] Defect ...

### Resources
**Analyse Notion**
https://www.notion.so/ferlab/CLIN-Soumission-des-donn-es-cliniques-formulaire-web-14e9730d63ea46f1b82e3dd03a15dce6

**Maquette Figma**
https://www.figma.com/file/xEHYxOCLtFUISHLQXP0PZa/formulaire-soumission?node-id=123%3A8229&viewport=491%2C693%2C0.6273972392082214
