### ISSUE TITLE
ETQ développeur, je veux sécuriser la console web de HAPI Fhir

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/clin-project#376]
### Feature

En tant que développeur membre de l'équipe Clin je veux pouvoir accéder à la console web sécurisée du serveur HAPI Fhir (clin-fhir-server).  

Pour se faire, on doit pouvoir détecter que l'appel provient de la console de HAPI et rediriger l'utilisateur sur Keycloak pour qu'il puisse s'authentifier s'il ne l'est pas.  Si l'appel provient du clin-frontend (client Axios), on ne doit pas rediriger l'utilisateur vers Keycloak mais renvoyer une 403 si le access_token de l'utilisateur est invalide. (Piste de solution: utiliser un header http custom pour déterminer la provenance de l'appel ou le host du referrer - à discuter)

Lors du callback de Keycloak, on devra écrire le token jwt dans un cookie (http only) qui devra être passé dans toutes les requêtes faites par HAPI Fhir de sorte que le AccessTokenInterceptor puisse lire et valider le token.  À noter que le domaine du cookie doit être le même que le domaine du serveur hapi-fhir afin que le browser envoi automatiquement le cookie dans toutes les requêtes faites à partir de la console web.

### Acceptance Criteria

**Scenario 1:** Accès à la console web
  - **Given:** L'utilisateur n'est pas authentifié
  - **When:** L'utilisateur accède à [HAPI_HOST]/hapi/fhir
  - **Then:** L'utilisateur est redirigé sur la page de login de Keycloak

**Scenario 2:** Redirection de Keycloak vers clin-fhir-server
  - **Given:** L'utilisateur s'authentifie dans Keycloak avec succès
  - **When:** L'utilisateur est redirigé vers un url de callback défini dans le serveur clin-fhir-server
  - **Then:** Un cookie http-only contenant le token jwt est ajouté et l'utilisateur est redirigé vers la console web de HAPI à laquelle il a maintenant accès.

**Scenario 3:** Une requête REST est lancée à partir de la console web HAPI
  - **Given:** L'utilisateur est authentifié
  - **When:** L'utilisateur lance une requête REST au serveur HAPI via la console web
  - **Then:** Le serveur HAPI valide le token provenant du COOKIE et exécute la requête de l'utilisateur.

**Scenario 4:** Une requête REST est lancée à partir d'un client REST (ex.: axios via clin-frontend)
  - **Given:** L'utilisateur est authentifié
  - **When:** L'utilisateur lance une requête REST au serveur HAPI via un client REST
  - **Then:** Le serveur HAPI valide le token provenant du HEADER HTTP "Authorization" et exécute la requête de l'utilisateur.

**Scenario 5:** Une requête REST est lancée à partir d'un client REST (ex.: axios via clin-frontend)
  - **Given:** L'utilisateur n'est pas authentifié
  - **When:** L'utilisateur lance une requête REST au serveur HAPI via un client REST
  - **Then:** Le serveur HAPI valide le token provenant du HEADER HTTP "Authorization" et renvoit une erreur 403 puisque le token est invalide.

### Sub-Tasks

- [ ] Identifier la provenance des requêtes (clin-frontend ou console web HAPI ou autre)
- [ ] Rediriger vers Keycloak SI la requête provient de la console web de HAPI
- [ ] Ajouter le cookie http only contenant le token jwt
- [ ] Gérer expiration / renouvellement du token jwt
- [ ] Valider le token à partir du cookie lorsque la requête provient de la console web de HAPI

### Defects
_List of defects/bugs found during QA._
- [ ] Aucun pour le moment

### Resources
https://hapifhir.io/hapi-fhir/docs/
