### ISSUE TITLE
Section HPO de la page 2 du formulaire 

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#378]
### Feature

Une fois que les termes sont à droite, il est possible de sauvegarder/mettre à jour/supprimer des termes dans FHIR

### Acceptance Criteria
- [ ] Le design a été appliqué et l'arbre est fonctionnel avec les termes anglais seulement pour l'instant.
- [ ] Il est possible de sélectionner et retirer des phénotypes
- [ ] Il est possible de sauvegarder et mettre a jour les phénotypes sélectionnés

### Sub-Tasks
- [x] Sauvegarde et mise à jour des observations CGH
- [x] Sauvegarde et mise à jour du résumé
- [x] Sauvegarde et mise à jour des observations HPO
- [ ] Ajout des observations HPO
- [ ] Suppression des observations HPO

### Testing Strategy
N'importe qui avec un accès en QA peut tester cette tâche

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

### Resources
Voir maquettes Figma
