### ISSUE TITLE
Page 2 - Barre de recherche HPO - Mettre en place la recherche de termes

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#419]
La barre de recherche permettant de trouver un terme HPO ne sera pas liée avec l'arbre dans le sens où le texte entré dans labarre ne filtrera pas l'arbre. La barre de recherche fera apparaitre une liste de terme dans laquelle un terme pourra être sélectionné et transférer à droite.

L'objectif de cette carte est donc de _**faire fonctionner la recherche seulement**_.

### Tasks
- [x] Ajouter la composante de recherche
- [x] Ajouter l'appel au service hpo dans le frontend
- [x] Invoquer le service hpo lorsqu'un terme est tapé et modifier les options du Autocomplete à partir des résultats
- [x] Lors de la sélection d'un résultat, construire une ressource hpo et l'ajouter à la liste pour qu'elle apparaisse dans la parie de droite.

---

### Sub-Tasks
- [x] Valider que le back-end est appelé et non un fichier json temporaire

![image](https://user-images.githubusercontent.com/64538118/91562082-99f2ea80-e90a-11ea-86c7-0c6d31c824b8.png)
