### ISSUE TITLE
Mettre à jour clin-proxy[liste des patients] pour prendre les données du nouveau index ES

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#497]
### Feature
A new ES index has been created to store the patients' list https://github.com/Ferlab-Ste-Justine/clin-project/issues/470
Update `clin-proxy-api` to retrieve the data from the new patient index.
Update `clin-frontend` to use the new patient list.

### Sub-Tasks
- [x] Update `clin-proxy-api` search service to retrieve the data from the new patient index.
- [x] Update `clin-frontend` to retrieve the new patient list and parse it correctly.
- [x] Update `clin-frontend` Search component to display the new patient list.

**Comment by YanLabCHU** [comment]
Done
