### ISSUE TITLE
Créer un nouveau profile pour les resources HPO

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#498]
### Feature
Créer une nouvelle resource HPO pour stocker les informations des phenotypes.
Présentement, les infomrations d'un HPO sont stocker dans une resource `Observation` avec un code `PHENO`. 

### Sub-Tasks
- [ ] Créer la nouvelle resource dans `clin-fhir`
- [ ] Ajouter un exemple d'une resource HPO dans `clin-fhir`
- [ ] S'assurer que les bonnes cardinalités sont utilisées
- [ ] Mettre à jour `clin-frontend` pour créer des resources HPO dans le formulaire patient
- [ ] Publier la nouvelle resource dans `clin-fhir-server`
- [ ] Publier le IG

**Comment by YanLabCHU** [comment]
Rempalcer par https://github.com/Ferlab-Ste-Justine/clin-project/issues/748
