### ISSUE TITLE
Mettre à jour l'ETL pour exporter les patients de Google Sheet vers ES

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#507]
### Feature
L'ETL doit aussi exporter les données des patients vers ES en suivant le format (tel que dans le mappings). 

### Acceptance Criteria
- [x] Les patients de Google Sheet doivent s'afficher dans la liste des patients en QA

### Sub-Tasks-
- [x] Mettre à jour `clin-fhir-etl` pour transformer les données des patients (avec leur service requeste etc.) dans le format de ES 
- [x] Ajouter le client ES en dépendance. 
- [x] Sauvegarder les données extraits dans ES.
