### ISSUE TITLE
Changement de status de la requête

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#606]
### Feature
Changement du status d'une requête au frontend et backend.

### Sub-Tasks
- [x] Mettre à jour le frontend pour changer le status d'une requête
- [x] Ajouter l'extension de status dans fhir
- [x] Mettre à jour le backend avec la nouvelle fhir guideline
- [x] Validation du status au backend
